#!/usr/bin/env bash

echo
echo "------------------------------------------------------------------------------------------------------------"
echo "Running get_from_trueblocks"
echo "------------------------------------------------------------------------------------------------------------"

if [ -z "$1" ]
then
    echo "Usage ./get_from_trueblocks <address>"
    exit
fi

echo "Downloading data from TrueBlocks for $1"

# get trueblocks' version of the address's history
chifra export --no_header --cache $1 >store/raw/trueblocks/$1.txt

# zip it so it doesn't take up so much room
gzip -f -n store/raw/trueblocks/$1.txt
