---
title: "trueblocks explorer"
subtitle: "other_data exploration"
output: html_notebook
---

```{r setup, message=FALSE}
require(tidyverse)
require(viridis)
require(readxl)
require(scales)
data.dir <- "../../trueblocks-tokenomics/other_data/"
```

For this R Notebook to work properly, you must define the proper data dir below. It expects the path of the "other_data" directory in the trueblocks-tokenomics repo. Please set your data.dir.

## Transactions.xlsx / Traces.xlsx

```{r trans.trace.data, message=FALSE}
Transactions <- readxl::read_xlsx(paste0(data.dir, "Transactions.xlsx"), range = "A5:CW255") %>% 
  rename(nTraces = `...1`) %>%
  gather(block.bucket, occurrences, -nTraces) %>%
  mutate(block.bucket = as.integer(block.bucket))

Transactions %>%
  #mutate(block.bucket = ntile(block.bucket, 25) * 2000000) %>%
  ggplot(aes(x = block.bucket, y = nTraces, fill = occurrences)) +
  geom_tile(color = "white", size=0) + 
  viridis::scale_fill_viridis(name = "log(n occurrences)", trans="pseudo_log", option = "A") +
  theme_minimal(base_size=8)
```

```{r trace.data, message=FALSE}
Traces <- readxl::read_xlsx(paste0(data.dir, "Traces.xlsx"), range = "A5:CW255") %>%
  rename(nTraces = `...1`) %>%
  gather(block.bucket, occurrences, -nTraces) %>%
  mutate(block.bucket = as.integer(block.bucket))

Traces %>%
  #mutate(block.bucket = ntile(block.bucket, 25) * 2000000) %>%
  ggplot(aes(x = block.bucket, y = nTraces, fill = occurrences)) +
  geom_tile(color = "white", size=0) + 
  viridis::scale_fill_viridis(name = "log(n occurrences)", trans="pseudo_log", option = "A", labels=scales::comma) +
  theme_minimal(base_size=8) +
  scale_x_continuous(labels = scales::comma)
```


## tokensByWeek.txt

```{r}
tokensByWeek <- read_delim(paste0(data.dir, "tokensByWeek.txt"), delim = "|") %>%
  gather("type", "value", c(-blockNum, -date)) %>%
  mutate(value = as.integer(value))

tokensByWeek %>%
  ggplot(aes(x = blockNum, y = value, color = type)) +
  geom_line() +
  theme_minimal(base_size=10) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma, name = "Cumulative count")

tokensByWeek %>%
  ggplot(aes(x = blockNum, y = value, color = type)) +
  geom_line() +
  theme_minimal(base_size=10) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma, name = "Cumulative count") +
  facet_grid("type")
```

## countsPer10000.txt

```{r}
countsPer10000 <- read_tsv(paste0(data.dir, "countsPer10000.txt")) %>%
  gather("type", "value", c(-blockNum, -date)) %>%
  mutate(blockNum = as.integer(blockNum))

countsPer10000 %>%
  filter(type %in% c('nEmpty','nFull')) %>%
  ggplot(aes(x=blockNum, y=value, color=type)) +
  geom_line() +
  theme_minimal(base_size=10) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_continuous(labels = scales::comma, name = "Cumulative count") 
```