---
title: "TB Chifra | Data Modeling & Predictive Accuracy"
author: "Matthieu Fournier"
date: "2022-08-25"
output:
  html_document:
    df_print: paged
---


# Data Prep
```{r}
nosis <- read.csv("gnosis-step-50000.csv")
nosis <- subset(nosis, select = -c(finalized))
head(nosis)
mn <- read.csv("mainnet-step-50000.csv")
mn <- subset(mn, select = -c(finalized))
head(mn)
sep <- read.csv("sepolia-step-5000.csv")
sep <- subset(sep, select = -c(finalized))
head(sep)
```

### Linear Subset Selection to predict TransactionsCnt
```{r}
require(leaps)
set.seed(2)

transCnt.model <- regsubsets(transactionsCnt~., data = mn, nvmax = 50, method = "forward")

par(mfrow=c(2,2))

tc.sum <- summary(transCnt.model)

plot(tc.sum$rss ,xlab="Number of Variables ", ylab="RSS", type="l")

plot(tc.sum$adjr2 ,xlab="Number of Variables ", ylab="Adjusted R Sq", type="l")
points(which.max(tc.sum$adjr2), tc.sum$adjr2[which.max(tc.sum$adjr2)], col = "blue", cex = 2, pch = 20)

plot(tc.sum$cp, xlab = "Number of Variables ", ylab = "CP", type = "l")
points(which.min(tc.sum$cp),tc.sum$cp[which.min(tc.sum$cp)], col = "blue", cex = 2, pch = 20)

plot(tc.sum$bic, xlab = "Number of Variables ", ylab = "BIC", type = "l")
points(which.min(tc.sum$bic),tc.sum$bic[which.min(tc.sum$bic)], col = "blue", cex = 2, pch = 20)

print(coef(transCnt.model, 9))


bic.opt <- lm(transactionsCnt ~ blockNumber, data = mn) 
# bic and cp optimize at 2 variables and the predictive analysis caps us at 35% 
resid.opt <- lm(transactionsCnt ~ blockNumber + timestamp + difficulty + gasUsed, data = mn)
# following optimal guidelines of residuals (RSS and adjrsq) we use 5 variables and double our predictive capabilities to 70%
plot(mn$timestamp, mn$transactionsCnt)
abline(resid.opt)
```








# Testing Model Predictive Accuracy and Noise
```{r}
library(dplyr)
PRESS <- function(linear.model) {
  #' calculate the predictive residuals
  pr <- residuals(linear.model)/(1-lm.influence(linear.model)$hat)
  #' calculate the PRESS
  PRESS <- sum(pr^2)
  
  return(PRESS)
}

pred_r_squared <- function(linear.model) {
  #' Use anova() to get the sum of squares for the linear model
  lm.anova <- anova(linear.model)
  #' Calculate the total sum of squares
  tss <- sum(lm.anova$'Sum Sq')
  # Calculate the predictive R^2
  pred.r.squared <- 1-PRESS(linear.model)/(tss)
  
  return(pred.r.squared)
}

pred_r_squared(bic.opt)
pred_r_squared(resid.opt)

```