#!/usr/bin/env bash

curl -X GET \
    "https://api.covalenthq.com/v1/1/address/$1/transactions_v2/?key=ckey_9162b2e801e84cce993a19101eb&page-size=5000" \
    -H "Accept: application/json" --output store/raw/$1.json


cat store/raw/covalent/$1.json | \
    jq ".data.items[] | .tx_hash, .block_height, .tx_offset" | \
    sed 's/"//g' | \
    tr '\n' '|' | \
    sed 's/|0x/+0x/g' | \
    tr '+' '\n' | \
    sed 's/|$//g' | \
    tr '|' '\t' | \
    sort >store/one/$1.txt
