#!/usr/bin/env bash

mkdir -p store/diff/in_cov_not_tb
mkdir -p store/diff/in_tb_not_cov
mkdir -p store/processed/covalent
mkdir -p store/processed/trueblocks
mkdir -p store/raw/covalent
mkdir -p store/raw/trueblocks
mkdir -p store/reasons/covalent
mkdir -p store/reasons/trueblocks
mkdir -p store/recons/covalent
mkdir -p store/recons/trueblocks

cd tools
make
cd -
