#!/usr/bin/env bash

mkdir -p store/raw/covalent
mkdir -p store/raw/trueblocks

mkdir -p store/processed/covalent
mkdir -p store/processed/trueblocks

mkdir -p store/diff/covalent_not_trueblocks
mkdir -p store/diff/trueblocks_not_covalent

mkdir -p store/recons/covalent
mkdir -p store/recons/trueblocks

mkdir -p store/reasons/covalent
mkdir -p store/reasons/trueblocks

cd tools
make
cd -
